spring:
  elasticsearch:
    rest:
      uris: ${virtual-url}:9200
      connection-timeout: 30s
      read-timeout: 30s
  rabbitmq:
    host: ${virtual-url}
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${virtual-url}:3306/baf?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: ${virtual-url}
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
    timeout: 3000ms
    connect-timeout: 3000ms
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

email:
  config:
    from: "短趣视频团队"
    password: EYRxmzT4S6vjXUHh
    host: smtp.163.com
    port: 465
    user: 13414800914@163.com
    expire-time: 300
jwt:
  secret: OASNDASINQWMEAOSCNK
  expiration: 86400000
  issuer: lytoyo

minio:
  endpoint: http://${virtual-url}:9000
  bucketName: baf
  accessKey: vQulpsLrq2qCy5orxttx
  secretKey: gtiiFqg3qyuYj1yU8F8zPSeozIzNWmIHt6rjzRVy
  secure: false
  url: http://${virtual-url}:9000/baf/

ffmpeg:
  path: E:\\ffmepg\\ffmpeg-7.1.1-full_build\\bin\\ffmpeg.exe

#/docker/ffmpeg/ffmpeg-git-amd64/ffmpeg
system:
  videoPath: D:/毕设项目/testFile/d658208e5ec5ba9e15bde72435f92509.mp4

virtual-url: 10.99.21.200

